name: CI/CD Pipeline

on:
  push:
  pull_request:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  run-linter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - 3.11
          - 3.12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run linter on Python ${{ matrix.python-version }}
        uses: chartboost/ruff-action@v1
        with:
          version: 0.6.5

  publish-to-pypi:
    needs: run-linter
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest

    environment: release

    permissions:
      id-token: write

    strategy:
      matrix:
        python-version:
          - 3.12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1.8
